services:
  redis:
    image: redis:7
    container_name: redis
    ports: 
      - "6379:6379"

  sockets:
    depends_on: [redis]
    build: 
      context: .
      dockerfile: sockets/Dockerfile
    env_file:
      - .env
    environment:
      - LUME_RUN_MODE=${LUME_RUN_MODE}
      - LUME_CONTROLLER_IP=${LUME_CONTROLLER_IP}
      - LUME_VERBOSE=${LUME_VERBOSE}
    ports:
      - "8888:8888/udp"

  postprocessing:
    depends_on: [redis]
    build: 
      context: .
      dockerfile: postprocessing/Dockerfile
    env_file:
      - .env
    environment:
      - LUME_RUN_MODE=${LUME_RUN_MODE}
      - LUME_CONTROLLER_IP=${LUME_CONTROLLER_IP}
      - LUME_VERBOSE=${LUME_VERBOSE}

  hmm:
    depends_on: [redis]
    build: 
      context: .
      dockerfile: hmm/Dockerfile
    env_file:
      - .env
    volumes:
      - ./models:/app/models  # Mount models directory
    environment:
      - LUME_RUN_MODE=${LUME_RUN_MODE}
      - LUME_CONTROLLER_IP=${LUME_CONTROLLER_IP}
      - LUME_VERBOSE=${LUME_VERBOSE}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    depends_on: [redis]
    build: 
      context: .
      dockerfile: db/Dockerfile
    env_file:
      - .env
    environment:
      - LUME_RUN_MODE=${LUME_RUN_MODE}
      - LUME_CONTROLLER_IP=${LUME_CONTROLLER_IP}
      - LUME_VERBOSE=${LUME_VERBOSE}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    depends_on: [redis]
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    env_file:
      - .env
    environment:
      - LUME_RUN_MODE=${LUME_RUN_MODE}
      - LUME_CONTROLLER_IP=${LUME_CONTROLLER_IP}
      - LUME_VERBOSE=${LUME_VERBOSE}
    ports:
      - "5173:5173"
      - "4000:4000"

  flightcontroller:
    depends_on: [redis]
    build: 
      context: .
      dockerfile: flightcontroller/Dockerfile
    env_file:
      - .env
    environment:
      - LUME_RUN_MODE=${LUME_RUN_MODE}
      - LUME_CONTROLLER_IP=${LUME_CONTROLLER_IP}
      - LUME_VERBOSE=${LUME_VERBOSE}
    ports:
      - "8889:8889"
      - "8890:8890"


# networks:
  # mybridge:
    # driver: bridge
